GitCandy/Controllers/SettingController.cs
using GitCandy.App_GlobalResources;
using GitCandy.Configuration;
using GitCandy.Filters;
using GitCandy.Git;
using GitCandy.Log;
using GitCandy.Models;
using GitCandy.Ssh;
using System;
using System.Composition;
using System.Web;
using System.Web.Mvc;

namespace GitCandy.Controllers
{
    [Administrator]
    [Export(typeof(SettingController))]
    public class SettingController : CandyControllerBase
    {
        public ActionResult Edit()
        {
            var config = UserConfiguration.Current;
            var model = new SettingModel
            {
                IsPublicServer = config.IsPublicServer,
                ForceSsl = config.ForceSsl,
                SslPort = config.SslPort,
                SshPort = config.SshPort,
                EnableSsh = config.EnableSsh,
                LocalSkipCustomError = config.LocalSkipCustomError,
                AllowRegisterUser = config.AllowRegisterUser,
                AllowRepositoryCreation = config.AllowRepositoryCreation,
                RepositoryPath = config.RepositoryPath,
                CachePath = config.CachePath,
                GitCorePath = config.GitCorePath,
                NumberOfCommitsPerPage = config.NumberOfCommitsPerPage,
                NumberOfItemsPerList = config.NumberOfItemsPerList,
                NumberOfRepositoryContributors = config.NumberOfRepositoryContributors,
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(SettingModel model)
        {
            var needRestart = false;
            var needRestartSshServer = false;

            if (ModelState.IsValid)
            {
                var config = UserConfiguration.Current;

                needRestart = (config.CachePath != model.CachePath);
                needRestartSshServer = config.SshPort != model.SshPort || config.EnableSsh != model.EnableSsh;

                config.IsPublicServer = model.IsPublicServer;
                config.ForceSsl = model.ForceSsl;
                config.SslPort = model.SslPort;
                config.SshPort = model.SshPort;
                config.EnableSsh = model.EnableSsh;
                config.LocalSkipCustomError = model.LocalSkipCustomError;
                config.AllowRegisterUser = model.AllowRegisterUser;
                config.AllowRepositoryCreation = model.AllowRepositoryCreation;
                config.RepositoryPath = model.RepositoryPath;
                config.CachePath = model.CachePath;
                config.GitCorePath = model.GitCorePath;
                config.NumberOfCommitsPerPage = model.NumberOfCommitsPerPage;
                config.NumberOfItemsPerList = model.NumberOfItemsPerList;
                config.NumberOfRepositoryContributors = model.NumberOfRepositoryContributors;
                config.Save();
                ModelState.Clear();
            }

            Logger.Info("Settings updated by {0}#{1}", Token.Username, Token.UserID);

            if (needRestart)
            {
                SshServerConfig.StopSshServer();
                HttpRuntime.UnloadAppDomain();
            }
            else if (needRestartSshServer)
            {
                SshServerConfig.RestartSshServer();
            }

            return View(model);
        }

        public ActionResult Restart(string conform)
        {
            if (string.Equals(conform, "yes", StringComparison.OrdinalIgnoreCase))
            {
                HttpRuntime.UnloadAppDomain();
                return RedirectToStartPage();
            }
            return View();
        }

        public ActionResult ReGenSsh(string conform)
        {
            if (string.Equals(conform, "yes", StringComparison.OrdinalIgnoreCase))
            {
                UserConfiguration.Current.HostKeys.Clear();
                foreach (var type in KeyUtils.SupportedAlgorithms)
                {
                    UserConfiguration.Current.HostKeys.Add(new HostKey { KeyType = type, KeyXml = KeyUtils.GeneratePrivateKey(type) });
                }
                UserConfiguration.Current.Save();

                SshServerConfig.RestartSshServer();

                return RedirectToAction("Edit");
            }
            return View();
        }
    }
}

GitCandy/Views/Setting/Edit.cshtml
@model GitCandy.Models.SettingModel

@{
    ViewBag.Title = string.Format(SR.Shared_TitleFormat, SR.Setting_EditTitle);
}

<h4>@SR.Setting_EditTitle</h4>


@using (Html.BeginForm("Edit", "Setting", FormMethod.Post))
{
    <dl class="dl-horizontal col-md-8">
        <dt>@Html.DisplayNameFor(s => s.IsPublicServer)</dt>
        <dd>
            <div class="switch" data-on-label="@SR.Shared_Yes" data-off-label="@SR.Shared_No">
                @Html.CheckBoxFor(s => s.IsPublicServer, new { data_size = "small" })
            </div>
        </dd>

        <dt>@Html.DisplayNameFor(s => s.ForceSsl)</dt>
        <dd>
            <div class="switch" data-on-label="@SR.Shared_Yes" data-off-label="@SR.Shared_No">
                @Html.CheckBoxFor(s => s.ForceSsl, new { data_size = "small" })
            </div>
        </dd>

        <dt>@Html.DisplayNameFor(s => s.EnableSsh)</dt>
        <dd>
            <div class="switch" data-on-label="@SR.Shared_Yes" data-off-label="@SR.Shared_No">
                @Html.CheckBoxFor(s => s.EnableSsh, new { data_size = "small" })
            </div>
        </dd>

        <dt>@Html.DisplayNameFor(s => s.SslPort)</dt>
        <dd>@Html.TextBoxFor(s => s.SslPort, new { @class = "form-control" })</dd>

        <dt>@Html.DisplayNameFor(s => s.SshPort)</dt>
        <dd>@Html.TextBoxFor(s => s.SshPort, new { @class = "form-control" })</dd>


        <dt>@Html.DisplayNameFor(s => s.LocalSkipCustomError)</dt>
        <dd>
            <div class="switch" data-on-label="@SR.Shared_Yes" data-off-label="@SR.Shared_No">
                @Html.CheckBoxFor(s => s.LocalSkipCustomError, new { data_size = "small" })
            </div>
        </dd>

        <dt>@Html.DisplayNameFor(s => s.AllowRegisterUser)</dt>
        <dd>
            <div class="switch" data-on-label="@SR.Shared_Yes" data-off-label="@SR.Shared_No">
                @Html.CheckBoxFor(s => s.AllowRegisterUser, new { data_size = "small" })
            </div>
        </dd>

        <dt>@Html.DisplayNameFor(s => s.AllowRepositoryCreation)</dt>
        <dd>
            <div class="switch" data-on-label="@SR.Shared_Yes" data-off-label="@SR.Shared_No">
                @Html.CheckBoxFor(s => s.AllowRepositoryCreation, new { data_size = "small" })
            </div>
        </dd>

        <dt>@Html.DisplayNameFor(s => s.RepositoryPath)</dt>
        <dd>@Html.TextBoxFor(s => s.RepositoryPath, new { @class = "form-control" })</dd>

        <dt>@Html.DisplayNameFor(s => s.CachePath)</dt>
        <dd>@Html.TextBoxFor(s => s.CachePath, new { @class = "form-control" })</dd>

        <dt>@Html.DisplayNameFor(s => s.GitCorePath)</dt>
        <dd>@Html.TextBoxFor(s => s.GitCorePath, new { @class = "form-control" })</dd>

        <dt>@Html.DisplayNameFor(s => s.NumberOfCommitsPerPage)</dt>
        <dd>@Html.TextBoxFor(s => s.NumberOfCommitsPerPage, new { @class = "form-control" })</dd>

        <dt>@Html.DisplayNameFor(s => s.NumberOfItemsPerList)</dt>
        <dd>@Html.TextBoxFor(s => s.NumberOfItemsPerList, new { @class = "form-control" })</dd>

        <dt>@Html.DisplayNameFor(s => s.NumberOfRepositoryContributors)</dt>
        <dd>@Html.TextBoxFor(s => s.NumberOfRepositoryContributors, new { @class = "form-control" })</dd>

        @if (!ViewData.ModelState.IsValid)
        {
        <dt></dt>
        <dd>@Html.ValidationSummary(true, SR.Setting_UpdateSettingsUnsuccessfull, new { @class = "alert alert-dismissable alert-danger" })</dd>
        }

        <dt></dt>
        <dd>
            <button type="submit" class="btn btn-primary">@SR.Shared_Save</button> &nbsp;
            <button type="reset" class="btn btn-inverse">@SR.Shared_Reset</button> &nbsp;
            @Html.ActionLink(SR.Setting_ReGenSsh, "ReGenSsh", null, new { @class = "btn btn-danger" }) &nbsp;
            @Html.ActionLink(SR.Shared_Restart, "Restart", null, new { @class = "btn btn-danger" }) &nbsp;
        </dd>
    </dl>
}

GitCandy/Views/Setting/ReGenSsh.cshtml
@{
    ViewBag.Title = string.Format(SR.Shared_TitleFormat, string.Format(SR.Setting_ReGenSshTitle));
}

<div class="panel panel-danger">
    <div class="panel-heading">
        <h4 class="panel-title">@SR.Shared_Conform</h4>
    </div>
    <div class="panel-body">
        @SR.Setting_ReGenSshWords
    </div>
</div>

<div>
    <div class="pull-left">
        @Html.ActionLink(SR.Shared_Back, "Edit", "Setting", null, new { @class = "btn btn-default" })
    </div>
    <div class="pull-right">
        @Html.ActionLink(SR.Shared_Generate, "ReGenSsh", "Setting", new { Conform = "Yes" }, new { @class = "btn btn-danger" })
    </div>
</div>

GitCandy/Views/Setting/Restart.cshtml
@{
    ViewBag.Title = string.Format(SR.Shared_TitleFormat, string.Format(SR.Setting_RestartTitle));
}

<div class="panel panel-danger">
    <div class="panel-heading">
        <h4 class="panel-title">@SR.Shared_Conform</h4>
    </div>
    <div class="panel-body">
        @SR.Setting_RestartWords
    </div>
</div>

<div>
    <div class="pull-left">
        @Html.ActionLink(SR.Shared_Back, "Edit", "Setting", null, new { @class = "btn btn-default" })
    </div>
    <div class="pull-right">
        @Html.ActionLink(SR.Shared_Restart, "Restart", "Setting", new { Conform = "Yes" }, new { @class = "btn btn-danger" })
    </div>
</div>